"""Model registry for harness + AXION."""

from axion.models.axion_model import AxionModel
from axion.models.centroid import CentroidDistanceModel

MODEL_REGISTRY = {
    "centroid_distance": CentroidDistanceModel,
    "axion": AxionModel,
    "axion_spear": AxionModel,
}


_AXION_KEYS = {
    "hidden",
    "latent",
    "depth",
    "mask_rates",
    "score_k",
    "dropout",
    "epochs",
    "batch_size",
    "lr",
    "weight_decay",
    "patience",
    "val_fraction",
    "latch_alpha",
    "latch_alpha_semi",
    "latch_alpha_semi_tiny",
    "latch_alpha_semi_huge",
    "latch_alpha_semi_huge_mid",
    "latch_alpha_semi_high_d",
    "latch_alpha_unsup_huge",
    "latch_alpha_unsup_large_mid",
    "latch_alpha_unsup_tiny",
    "mae_weight",
    "nll_weight",
    "mae_weight_semi",
    "nll_weight_semi",
    "mae_weight_unsup_huge",
    "nll_weight_unsup_huge",
    "semi_epoch_boost",
    "tiny_epoch_boost",
    "pca_dim",
    "pca_threshold",
    "pca_variance",
    "pca_k_min",
    "hedge_alpha",
    "hedge_alpha_semi_high_d",
    "hedge_alpha_nlp",
    "hedge_alpha_semi_nlp",
    "hedge_alpha_semi_nlp_multi",
    "robust_latch_unsup_huge",
    "x_latch_alpha_unsup_huge",
    "x_latch_max_d",
    "contam_trim_frac",
    "contam_trim_warmup",
    "contam_trim_every",
    "latch_alpha_unsup_low_d",
    "nlp_raw_d_min",
    "vis_alpha_semi",
    "disagree_alpha_semi",
    "hpd_alpha_semi",
    "hpd_alpha_semi_huge",
    "c_hedge_alpha_semi",
    "c_hedge_alpha_semi_huge",
    "vis_alpha_semi_huge",
    "disagree_alpha_semi_huge",
    "bank_weight_semi",
    "learn_bank_weights",
    "calix_semi",
    "contrastive_weight",
    "latch_shrinkage",
    "semi_loss_curriculum",
    "block_prob",
    "use_interaction",
    "interaction_rank",
    "ensemble_heads",
    "true_ensemble",
    "score_batch_size",
    "score_batch_size_oom_fallback",
    "dataloader_num_workers",
    "tiny_n_safe_hw",
    "tiny_n_safe_threshold",
    "tiny_n_score_batch_size",
    "tiny_n_dataloader_num_workers",
    "mid_n_safe_hw",
    "mid_n_score_batch_size",
    "mid_n_dataloader_num_workers",
    "huge_n_safe_hw",
    "huge_n_safe_threshold",
    "huge_n_score_batch_size",
    "huge_n_dataloader_num_workers",
    "mcs_pack_masks",
    "vectorized_masks",
    "spear",
    "spear_gamma",
    "spear_gamma_nlp",
    "spear_pairs",
    "spear_epochs",
    "spear_lr",
    "spear_hidden",
    "spear_classical_only",
    "spear_soft_ap",
    "spear_skip_huge_n",
    "spear_huge_n_threshold",
    "spear_skip_tiny_n",
    "spear_tiny_n_threshold",
    "spear_allow_datasets",
    "spear_rank_fuse",
    "spear_fuse",
    "spear_fuse_nlp",
    "spear_tail_q",
    "spear_tail_soft",
    "rare",
    "rare_gamma",
    "rare_gamma_cover",
    "rare_pairs",
    "rare_epochs",
    "rare_lr",
    "rare_hidden",
    "rare_huge_n_threshold",
    "rare_max_fit_n",
    "rare_skip_cover",
    "rare_allow_datasets",
    "edge",
    "edge_gamma_cv",
    "edge_gamma_nlp",
    "edge_pairs",
    "edge_epochs",
    "edge_lr",
    "edge_hidden",
    "edge_skip_imdb",
    "edge_max_fit_n",
    "edge_whiten",
    "edge_whiten_dim",
    "edge_knn_view",
    "edge_knn_k",
    "edge_advanced_allow_datasets",
    "edge_skip_fashion_advanced",
    "nest",
    "nest_gamma_cv",
    "nest_gamma_nlp",
    "nest_pairs",
    "nest_epochs",
    "nest_lr",
    "nest_hidden",
    "nest_knn_k",
    "nest_skip_imdb",
    "nest_max_fit_n",
    "cv_knn",
    "cv_knn_alpha_semi",
    "cv_knn_memory_cap",
    "cv_knn_neighbors",
    "cv_knn_skip_fashion",
    "cv_knn_allow_datasets",
    "cv_lof",
    "cv_lof_alpha_semi",
    "cv_lof_method",
    "cv_lof_mode",
    "cv_lof_neighbors",
    "cv_lof_memory_cap",
    "cv_lof_whiten",
    "cv_lof_whiten_dim",
    "cv_lof_allow_datasets",
    "nlp_lof",
    "nlp_lof_alpha_semi",
    "nlp_lof_method",
    "nlp_lof_mode",
    "nlp_lof_fuse",
    "nlp_lof_tail_q",
    "nlp_lof_tail_soft",
    "nlp_lof_neighbors",
    "nlp_lof_memory_cap",
    "nlp_lof_whiten",
    "nlp_lof_whiten_dim",
    "nlp_lof_allow_datasets",
    "profile_router",
    "research_embeds",
    "ecod",
    "ecod_alpha",
    "copod",
    "copod_alpha",
    "goad",
    "goad_alpha",
    "goad_transforms",
    "goad_epochs",
    "dataset_hint",
    "device",
    "seed",
    "max_train_samples",
}


def build_model(name: str = "axion", **kwargs):
    if name not in MODEL_REGISTRY:
        raise KeyError(f"Unknown model {name!r}; known={list(MODEL_REGISTRY)}")
    cls = MODEL_REGISTRY[name]
    # Drop nulls from YAML
    kwargs = {k: v for k, v in kwargs.items() if v is not None}
    if name == "centroid_distance":
        allowed = {"whiten", "eps"}
        kwargs = {k: v for k, v in kwargs.items() if k in allowed}
    elif name in ("axion", "axion_spear"):
        kwargs = {k: v for k, v in kwargs.items() if k in _AXION_KEYS}
        if name == "axion_spear":
            kwargs.setdefault("spear", True)
    return cls(**kwargs)
